### ISSUE TITLE
[Unit Test]mocha command giving ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Bistard** [Bistard/MarkdownNote#63]
**Describe the bug**
mocha seems does not to support `window` global variable after executing the command script `npm test`.

**Error**
```
ReferenceError: window is not defined
    at Object.<anonymous> (D:\dev\ref\electron-play-ground\src\base\common\animation.ts:49:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\dev\ref\electron-play-ground\src\base\browser\basic\scrollable\scrollable.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\dev\ref\electron-play-ground\test\base\common\scrollable.test.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\dev\ref\electron-play-ground\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.exports.requireOrImport (D:\dev\ref\electron-play-ground\node_modules\mocha\lib\nodejs\esm-utils.js:60:20)
    at async Object.exports.loadFilesAsync (D:\dev\ref\electron-play-ground\node_modules\mocha\lib\nodejs\esm-utils.js:103:20)
    at async singleRun (D:\dev\ref\electron-play-ground\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (D:\dev\ref\electron-play-ground\node_modules\mocha\lib\cli\run.js:374:5)
npm ERR! Test failed.  See above for more details.
```

**Desktop (please complete the following information):**
 - windows 10

**Comment by Bistard** [comment]
fix by installing `jsdom-global` (note that, seems like installing `jsdom` local storage will not work).

see more from 
https://stackoverflow.com/questions/34059644/mocha-command-giving-referenceerror-window-is-not-defined
